### ISSUE TITLE
[Question] Database with doodba

### ISSUE THREAD

**Issue by Saran440** [ecosoft-odoo/nxpo#10]
It's work with new database **devel** in port localhost:14081.
BUT I have questions with database

1. How can I restore database with doodba?
2. How can I query my database that restore (i.e. devel2)
3. Can I use pgadmin for look database or not?

**Comment by kittiu** [comment]
All questions require basic knowledge of Doodba. @newtratip please help if you know the answer.

1. How can I restore database with doodba?

You need to get into odoo container and make restore as normal (you can pass database.sql to resetore in private folder). I just ask from internet as "how to access docker container" and got the following
https://stackoverflow.com/questions/30172605/how-do-i-get-into-a-docker-containers-shell
```
kittiu@ecosoft:~/doodba/doodba14$ docker exec -it doodba14_odoo_1 bash
odoo@2d3efd3121f8:/opt/odoo$ psql
psql (13.1 (Debian 13.1-1.pgdg90+1))
Type "help" for help.

devel=# 
```

2. How can I query my database that restore (i.e. devel2) -> As above.
3. Can I use pgadmin for look database or not? -> You can, but again, you need to understand basic Docker.

Or just use this -> http://localhost:14081 ($version+081)

**Comment by Saran440** [comment]
okay, I got it. In port 14081 can select other database
![Selection_001](https://user-images.githubusercontent.com/20896369/103470671-920af180-4da7-11eb-842c-499f858a817c.png)

Thank you for your advised me.
